# Generated by Django 2.0.3 on 2018-04-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replay',
            options={'ordering': ['-correct', 'replay_up', 'created'], 'verbose_name': 'Reposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AddField(
            model_name='replay',
            name='thread',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.Thread', verbose_name='tópico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
