# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170425_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_embendded',
            field=models.BooleanField(default=False, verbose_name='é um video?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.Course', verbose_name='Curso'),
        ),
    ]
